# Generated by Django 4.0.3 on 2022-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_comp_contact_extracurr_contact_finance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=20)),
                ('phoneno', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='Comp',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Extracurr',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Finance',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Gender',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='HWSW',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Literacy',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Living',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Sports',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Teams',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gap',
            field=models.CharField(default='', max_length=1),
        ),
    ]
