# Generated by Django 4.0.3 on 2022-04-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
