# Generated by Django 4.0.3 on 2022-04-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('phoneno', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
