# Generated by Django 4.0.3 on 2022-04-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_feedback_email_alter_feedback_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(default='', max_length=50),
        ),
    ]
