# Generated by Django 4.0.3 on 2022-04-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_feedback_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='me',
        ),
    ]
