# Generated by Django 4.0.3 on 2022-04-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_message_feedback_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
