# Generated by Django 4.0.3 on 2022-04-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
